# Generated by Django 5.2.5 on 2025-09-04 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parent',
            name='mother_occupation',
            field=models.CharField(default='Not specified', max_length=100),
            preserve_default=False,
        ),
    ]
