# Generated by Django 5.2.5 on 2025-09-08 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Xy9h3iYvVRSEwjC22C2BlmUd50ESnYbN', editable=False, max_length=32, unique=True),
        ),
    ]
