# Generated by Django 5.2.5 on 2025-09-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='2WJubSG9eaojl8ixQSdPPLlGOrs3scNB', editable=False, max_length=32, unique=True),
        ),
    ]
