# Generated by Django 5.2.5 on 2025-09-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='Gb21RbswZqF7RXD8gDrakIMMOHL8Ok6k', editable=False, max_length=32, unique=True),
        ),
    ]
