# Generated by Django 5.2.5 on 2025-09-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='7t8zFR5TVfMq5FFDa18zzxhQSR5aeduC', editable=False, max_length=32, unique=True),
        ),
    ]
