# Generated by Django 5.2.5 on 2025-09-16 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='WX8IYv0nFZRUYd39p1R4OW4wFBaCJHbM', editable=False, max_length=32, unique=True),
        ),
    ]
